# WARNING: please contact the security team before modifying this file

name: Semgrep

on:
  # Scan changed files in PRs, only report new findings (existing
  # findings in the repository are ignored).
  pull_request:

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source with GitHub Actions Checkout.
      - uses: actions/checkout@v3

      # Run the "semgrep ci" command on the command line of the docker image.
      - run: semgrep ci
        env:
          # Set hard-coded rulesets, viewable in logs.
          SEMGREP_RULES: auto p/security-audit p/terraform #more at semgrep.dev/explore
